### ISSUE TITLE
[Question] On window size and threshold

### ISSUE THREAD

**Issue by shoegazerstella** [kvsphantom/instrument-recognition-polyphonic#2]
Hi, 
Nice work you've done.
I am trying to reproduce some of the experiment also in conjunction with [this](https://arxiv.org/abs/1511.05520) paper you also mention in your work.

I have some questions about the window size. 
In your thesis you say a window size of 3 seconds is preferred. Although you only experiment only up until 5 seconds. Did your experiment with a duration > 5 seconds were super bad or you simply decided not to try with such a configuration?

Another question about the threshold for the activation data. I am currently using a threshold of 0.5 to assign the label 1 to each instrument, as suggested in the paper.
According to your work, would you say that for a window of 5s a threshold of .4 or .45 would be more appropriate?

Thanks a lot!

**Comment by vskadandale** [comment]
Hi,

I didn't test window lengths bigger than 5s. I thought that it will be too big a window that might possibly miss out on many significant temporally localized musical events.
With regard to the threshold, I experimentally determined the threshold value for the traditional machine learning method (Support Vector Machines). This value happened to be 0.4 or 0.45. For the sake of time, I retained these values for the deep learning method as well. Please refer to 4.1.3 section of [this](https://github.com/kvsphantom/instrument-recognition-polyphonic/blob/master/Venkatesh_SMC_THESIS.pdf) document to see how I arrived at these values.

**Comment by shoegazerstella** [comment]
Hi,
Thanks a lot for the clarification.
I decided to go for the .5 threshold and 5seconds as like this the dataset is quite consistent already.
Just an heads up: I did some small changes to the optimizer and learning rate. Also re-organized a bit the labels and included the version 2 of the MedleyDB (only 23 songs as for many other all the activation and metadata information were missing). By now my best model is the CNN one that's very accurate on my test set.
Would you suggest me some other dataset on which I can really test the model? Maybe a more diverse dataset in terms of sampling rate etc..
Thanks!
